=== sa7mon/COMP2150-WebServices/labSchemaEclipse/infoboxSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="https://danthesalmon.com/infoboxSchema" xmlns:tns="https://danthesalmon.com/infoboxSchema" elementFormDefault="qualified">

    <element name="infoBox" type="tns:infoBox"></element>
    
    <complexType name="infoBox">
    	<sequence>
    		<element name="author" type="string" maxOccurs="unbounded" minOccurs="0"></element>
    		<element name="originalTitle" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="displayTitle" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="language" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="genre" type="string" maxOccurs="unbounded" minOccurs="1"></element>
    		<element name="publisher" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="publicationDate" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="pages" type="integer" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>
</schema>

=== sa7mon/COMP2150-WebServices/labSchemaEclipse/infoboxInstance.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:infoBox xmlns:tns="https://danthesalmon.com/infoboxSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://danthesalmon.com/infoboxSchema infoboxSchema.xsd ">
  <tns:author>Yann Martel</tns:author>
  <tns:originalTitle>LIfe of Pi</tns:originalTitle>
  <tns:displayTitle>Life of Pi</tns:displayTitle>
  <tns:language scheme="RTF5646">
    <tns:name>en-US</tns:name>
  </tns:language>
  <tns:genre>Fiction</tns:genre>
  <tns:publisher>Knopf Canda</tns:publisher>
  <tns:publicationDate scheme="W3C-DTF">
    <tns:name>2001-09</tns:name>
  </tns:publicationDate>
  <tns:pages>401</tns:pages>
</tns:infoBox>
