=== sa7mon/COMP2150-WebServices/prjXMLValidation/collection.dtd
<?xml version="1.0" encoding="utf-8" ?>
<!ELEMENT catalog (product)>
	<!ELEMENT product (item_number, price, description, 
                     color, product_image+)>
		<!ATTLIST product 
			department (Mens|Womens|Unisex) #REQUIRED
			size (S|M|L|XL|XXL) #REQUIRED>	
		<!ELEMENT item_number (#PCDATA)>
		<!ELEMENT price (#PCDATA)>
			<!ATTLIST price 
			  currency CDATA #REQUIRED
			  sale (Yes|No) "No">
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT color (#PCDATA)>
		<!ELEMENT product_image (#PCDATA)>

=== sa7mon/COMP2150-WebServices/prjXMLValidation/collection.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE catalog SYSTEM "collection.dtd">
<catalog>
  <product department="Mens" size="S">
    <item_number>123456</item_number>
    <price currency="USD" sale="Yes">14.67</price>
    <description>Blue Knit Cardigan</description>
    <color>Blue</color>
    <product_image>123456_front.png</product_image>
    <product_image>123456_back.png</product_image>
  </product>
  <product department="Womens" size="L">
    <item_number>234567</item_number>
    <price currency="USD" sale="No">45.33</price>
    <description>Khaki Pants</description>
    <color>Tan</color>
    <product_image>234567_front.png</product_image>
    <product_image>234567_back.png</product_image>
  </product>
</catalog>
